services:
  test_reservation_db:
    image: postgres:16
    container_name: test_reservation_db
    ports:
      - "5432:5432"
    env_file:
      - .env_test
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 50
    restart: always

  test_reservation_app:
    build:
      context: ..
      dockerfile: deploy/reservation/Dockerfile
    container_name: test_reservation_app
    env_file:
      - .env_test
    ports:
      - "8000:8000"
    depends_on:
      test_reservation_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://test_reservation_app:8000/api/v1/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 50
      
  tests:
    build:
      context: ..
      dockerfile: deploy/reservation/tests/Dockerfile
    container_name: tests
    env_file:
      - .env_test
    depends_on:
      test_reservation_db:
        condition: service_healthy
      test_reservation_app:
        condition: service_healthy

