services:
  reservation_db:
    image: postgres:16
    container_name: reservation_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 50
    restart: always

  reservation_app:
    build:
      context: ..
      dockerfile: deploy/reservation/Dockerfile
    container_name: reservation_app
    env_file:
      - .env
    depends_on:
      reservation_db:
        condition: service_healthy

volumes:
  pg_volume:

